### ISSUE TITLE
"addr:" in address

### ISSUE THREAD

**Issue by vsantalov** [mordak/playbook-dev-tools#10]
ubuntu 14.04 64 bit
Blackberry Passport
SDK 10.3.1

build.sh creates addresses in this format    http://addr:myipaddress:8888/pbinstall.sh
It was an easy workaround to remove "addr:" from the two instances in pbinstall.sh. After that everything worked.

ps
Great thanks for your work on term48 and gcc on bb10!

**Comment by mordak** [comment]
Thanks for reporting! Not sure how I missed that one, but just pushed a fix. Thanks!
