### ISSUE TITLE
`bbndk-env.sh` not found

### ISSUE THREAD

**Issue by xubin990510** [mordak/playbook-dev-tools#12]
I just made a fresh install of BB Momentics IDE and cloned this repository. Here's what the directory structure looks like:

```
total 12
drwxr-xr-x 8 johnson johnson 4096 Jul  6 18:19 bbndk
drwxr-xr-x 3 johnson johnson 4096 Jul  6 18:19 momentics-workspace
drwxr-xr-x 9 johnson johnson 4096 Jul  6 18:12 playbook-dev-tools
```

But when I go into `playbook-dev-tools` and run `./build.sh -b /home/johnson/Programming/BB/bbndk`, it tells me:

```
Cannot source /home/johnson/Programming/BB/bbndk/bbndk-env.sh. Pass -b [path] to specify.
```

My `.run` file downloaded from BlackBerry is named `momentics-2.1.2-201503050937.linux.x86.run`, and this is what's inside `/home/johnson/Programming/BB/bbndk`:

```
total 64
drwxr-xr-x  2 johnson johnson 4096 Jul  6 18:12 archive
drwxr-xr-x 25 johnson johnson 4096 Jul  6 18:08 bootstrap
-rwxr-xr-x  1 johnson johnson 2698 Jul  6 18:08 build.sh
drwxr-xr-x  2 johnson johnson 4096 Jul  6 18:12 conf
-rw-r--r--  1 johnson johnson 6513 Jul  6 18:08 lib.sh
-rwxr-xr-x  1 johnson johnson  159 Jul  6 18:08 localserver.rb
drwxr-xr-x  2 johnson johnson 4096 Jul  6 18:12 packages
drwxr-xr-x  2 johnson johnson 4096 Jul  6 18:12 pbhome
-rw-r--r--  1 johnson johnson 1477 Jul  6 18:08 pbinstallhead.sh
-rwxr-xr-x  1 johnson johnson  791 Jul  6 18:08 pbpkgadd
-rw-r--r--  1 johnson johnson 1248 Jul  6 18:08 profile
-rw-r--r--  1 johnson johnson  265 Jul  6 18:08 qconf-override.mk
-rw-r--r--  1 johnson johnson 6543 Jul  6 18:08 README.md
drwxr-xr-x  2 johnson johnson 4096 Jul  6 18:12 work
```

**Comment by mordak** [comment]
You bbndk folder should contain the blackberry tools, so it should contain the qde executable, and directories for the target SDKs that you have installed. Your directory listing there is for the playbook-dev-tools directory, which doesn't contain the bbndk-env.sh file. The bbndk-env.sh file is provided by the BlackBerry Developer Tools when you install a target SDK. 

Momentics should prompt you to install a target SDK when you launch it. The one I am working with is bbndk-env_10_3_1_995.sh. When you install an SDK, you should get a target_<version> directory in the bbndk directory, and a corresponding bbndk-env_<version>.sh file in the root of the bbndk folder.

If you don't have an SDK installed, you can follow the [directions](https://developer.blackberry.com/native/downloads/releasenotes/#upgrading) provided by BlackBerry to get set up. Generally, you just open Momentics, select Help -> Update API Levels, select the most recent SDK, and then Install. It takes awhile to download, but then you should have the bbndk-env.sh file, and the build script should be able to find it.

**Comment by lordfolken** [comment]
in the bbndk directory: 
./sdkinstall --install 10_3_1_995 

This will download all the things necessary for the ndk to be actually installed and functional. Then follow the instructions in the playbook-dev-tools readme.md
