### ISSUE TITLE
Term48 and C compiler on Blackberry Q10

### ISSUE THREAD

**Issue by blackunix** [mordak/playbook-dev-tools#19]
Hi mordak,

How can I get a Compiler on my Blackberry Q10 (I believe it has BB OS 10) via Windows 8? Is this possible and if yes how? Sorry everyone I am a complete newbie to the subject. I would really appreciate some advice, hints, tips... Many thanks in advance.

**Comment by blackunix** [comment]
Oh, I forgot to mention that I am keen on using a C compiler not the preinstalled Python one...

**Comment by stmblfrcr** [comment]
Just follow the description here https://github.com/mordak/playbook-dev-tools/blob/master/README.md. It's quite clear. Better do this on a Linux machine.

**Comment by mordak** [comment]
Hi blackunix,

No, the tooling in this repo will not work on Windows. You will need either a linux machine (ubuntu will work) or OS X. 

From your Windows 8 machine, it should not be too hard to spin up a Linux virtual machine using virtualbox or vmware. You can do the cross compilation and installing from there.

**Comment by blackunix** [comment]
Hi everyone many thanks for your kind advice and help. I'll try this with vmware. If you don't mind I'll ask in case new questions arise. Thanks again, it's great you're being so helpful! :)
