### ISSUE TITLE
Non-listed dependency

### ISSUE THREAD

**Issue by extrowerk** [mordak/playbook-dev-tools#22]
On current Manjaro (Linux Singularity 5.4.40-1-MANJARO #1 SMP PREEMPT Sun May 10 14:17:40 UTC 2020 x86_64 GNU/Linux) build.sh fails because missing "zip" executable. Zip should be added to the dependency/requiments list.

**Comment by mordak** [comment]
Sure. I updated the README.

This repository is generally unmaintained, so I am a bit surprised to see anyone building it. Especially on Manjaro, which already has a much much much better package build system than what this provides.

What is this being used for on Manjaro?

**Comment by extrowerk** [comment]
I am trying to help here: https://forums.crackberry.com/blackberry-10-os-f269/breathing-new-life-into-bb10-1184578/
with 
https://github.com/BerryFarm/berrymuch
and to get better overwiev wanted to see how stuff works.

**Comment by mordak** [comment]
Oh, neat! Good luck with it!
